---
title: "Plumber example"
author: "Francisco Sanchez-Saez"
date: "last-modified" 
editor: source
format:
  html:
    toc: true
    toc-location: left
    theme: cerulean
    css: style.css
    embed-resources: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This example relies in the nice tutorial from Andrew Heiss: <https://www.andrewheiss.com/blog/2024/01/12/diy-api-plumber-quarto-ojs/_book/>

First, the step in make <https://www.make.com/en> is done and the content of <https://www.goodreads.com/> is been copied to my [googledoc sheet](https://docs.google.com/spreadsheets/d/1xZEfjyxiH5SQQ-UYSyKN0UCA6lsd7twRsyzAAGGzn7o/edit#gid=0)

Then, it is time to move to R.

# Go direct

```{r}
# retrieve directly the data-------------------------------------------------
library(tidyverse)
library(googlesheets4)

gs4_deauth()  # The sheet is public so there's no need to log in
local_gs4_quiet()  # Turn off the googlesheets messages

books_raw <- read_sheet("https://docs.google.com/spreadsheets/d/1xZEfjyxiH5SQQ-UYSyKN0UCA6lsd7twRsyzAAGGzn7o/edit#gid=0")

last_five_books <- books_raw |> 
  mutate(timestamp = dmy_hms(user_date_created)) |> 
  arrange(desc(timestamp)) |> 
  select(timestamp, author_name, title) |> 
  slice_head(n = 5)

last_five_books

```



# Go with obs

```{ojs}
d3 = require('d3')

books = await d3.json(
  // This is my live API so it runs in your browser.
  // Use your local API URL on your computer.
  "http://127.0.0.1:6312/books?year=2024"
  //"https://api.andrewheiss.com/books_simple?year=2024"
)

Plot.plot({
  title: books.count[0] + " books read in 2024",
  y: {
    label: "Books read",
    grid: false,
    percent: false
  },
  x: {
    label: "Month",
    domain: books.monthly_count.map(d => d.read_month_fct),
  },
  marks: [
    Plot.ruleY([0]),
    Plot.axisX({label: null, ticks: null}),
    Plot.axisY({label: null, ticks: null}),

    Plot.barY(books.monthly_count, {
      x: "read_month_fct", 
      y: "count", 
      fill: "#f3752f",
      tip: {
        format: {
          x: true,
          y: true
        }
      }
    })
  ]
})

```

